// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "kootah/domain"

	mock "github.com/stretchr/testify/mock"
)

// Kootah is an autogenerated mock type for the Kootah type
type Kootah struct {
	mock.Mock
}

// CreateURL provides a mock function with given fields: ctx, redirectTo
func (_m *Kootah) CreateURL(ctx context.Context, redirectTo string) (domain.UID, error) {
	ret := _m.Called(ctx, redirectTo)

	var r0 domain.UID
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.UID); ok {
		r0 = rf(ctx, redirectTo)
	} else {
		r0 = ret.Get(0).(domain.UID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, redirectTo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRedirectTo provides a mock function with given fields: ctx, urlID
func (_m *Kootah) GetRedirectTo(ctx context.Context, urlID domain.UID) (string, error) {
	ret := _m.Called(ctx, urlID)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, domain.UID) string); ok {
		r0 = rf(ctx, urlID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.UID) error); ok {
		r1 = rf(ctx, urlID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
